"""Adds repostories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/stout-grpc-examples repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of stout-grpc-examples follow the Bazel build
# instructions at https://github.com/3rdparty/stout-grpc-examples.
########################################################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("//3rdparty/stout-grpc:repos.bzl", stout_grpc_repos="repos")

def repos(external = True, repo_mapping = {}):

    stout_grpc_repos(
        repo_mapping = repo_mapping
    )

    if external and "com_github_stout_grpc_examples" not in native.existing_rules():
        # For now fail with an error message when someone tries to depend
        # externally on stout-grpc-examples.
        # In the future perhaps we'd want to drop the fail(...) and update and
        # uncomment the git repo block below.
        #
        #git_repository(
        #    name = "com_github_stout_grpc_examples",
        #    remote = "https://github.com/3rdparty/stout-grpc-examples",
        #    commit = "...",
        #    shallow_since = "...",
        #    repo_mapping = repo_mapping,
        #)
        #
        fail(
            "You are trying to import a piece of example code in your project. " +\
            "This is likely not what you want, but if it is, give us a shout on github: " +\
            "https://github.com/3rdparty/stout-grpc-examples/issues"
        )
