"""Adds repostories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/stout-grpc-examples repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of stout-grpc-examples follow the Bazel build
# instructions at https://github.com/3rdparty/stout-grpc-example.
########################################################################

load("//3rdparty/stout-grpc:repos.bzl", stout_grpc_repos = "repos")

def repos(external = True, repo_mapping = {}):
    stout_grpc_repos(
        repo_mapping = repo_mapping,
    )
